# Generated by Django 4.2.16 on 2026-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='video_file',
            field=models.FileField(blank=True, help_text="To'g'ridan-to'g'ri brand videosini yuklash (ixtiyoriy)", null=True, upload_to='brands/videos/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='video_url',
            field=models.URLField(blank=True, help_text='Brand uchun YouTube yoki Vimeo video havolasi (ixtiyoriy)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='video_file',
            field=models.FileField(blank=True, help_text="To'g'ridan-to'g'ri video fayl yuklash (mp4, webm)", null=True, upload_to='works/videos/'),
        ),
    ]
