# Generated by Django 4.2.16 on 2026-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='video_url',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project_year',
            field=models.PositiveIntegerField(default=2026, help_text='Loyiha tashkil topgan yili', verbose_name='Loyiha yili'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='video_file',
            field=models.FileField(default='', help_text="To'g'ridan-to'g'ri video fayl yuklash (.mp4)", upload_to='projects/videos/'),
            preserve_default=False,
        ),
    ]
