# Generated by Django 4.2.16 on 2026-07-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_brand_video_url_remove_casestudy_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='video_file',
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='projects/videos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.casestudy')),
            ],
            options={
                'verbose_name': 'Loyiha video',
                'verbose_name_plural': 'Loyiha videolari',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.casestudy')),
            ],
            options={
                'verbose_name': 'Loyiha rasmlari',
                'verbose_name_plural': 'Loyiha rasmlari',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
