# Generated by Django 4.2.16 on 2026-07-03 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0006_remove_brand_video_file_remove_casestudy_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Bloklash sababi')),
                ('blocked_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
